### ISSUE TITLE
Use build.rs to generate Tuple, List, HasLength, and unary type/const synonyms

### ISSUE THREAD

**Issue by kwf** [boltlabs-inc/dialectic#34]
Right now these pieces of boilerplate were generated once using a bespoke python script, but it would be better for them to be generated by `build.rs` to ensure they are more maintainable. This should have no externally visible consequences whatsoever, it's merely an internal refactor of relatively low priority.

**Comment by sdleffler** [comment]
Do we still have the source of this Python script? Can we port it to Rust and then drop that directly into the build.rs?

Guess we could also do it w/ syn/quote from the build.rs.
